name: handle manifest PR
on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:
      - main


jobs:
  call-manifest-pr-action:
    runs-on: ubuntu-latest
    steps:
      - name: handle manifest PR
        if: >
          !(contains(github.event.pull_request.title, 'manifest-pr-skip') ||
            contains(github.event.pull_request.body, 'manifest-pr-skip'))
        uses: nrfconnect/action-manifest-pr@main
        with:
          token: ${{ secrets.NCS_GITHUB_TOKEN }}
          manifest-pr-title-details: ${{ github.event.pull_request.title }}
